version: '3.8'

services:
  # Zookeeper: trình quản lý cho Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka Broker (máy chủ Kafka)
  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  db: 
    image: "mysql:8.0"
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./main.sql:/docker-entrypoint-initdb.d/main.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
  service-discovery:
    build:
      context: .
      dockerfile: ./service-discovery/Dockerfile
      args:
        MODULE_PATH: service-discovery
    ports:
      - "8761:8761"
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_HOST_NAME=service-discovery
      - PORT=8761

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
      args:
        MODULE_PATH: api-gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRETKEY=${JWT_SECRETKEY}
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_SERVER_URL=http://service-discovery:8761/eureka/
      - EUREKA_SERVER_URI=http://service-discovery:8761
      - PORT=8080
    depends_on:
      - service-discovery
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
      args:
        MODULE_PATH: auth-service
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRETKEY=${JWT_SECRETKEY}
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_SERVER_URL=http://service-discovery:8761/eureka/
      - PORT=8081
      - URL=http://auth-service:8081
      - KAFKA_SERVER=broker:29092
    depends_on:
      - service-discovery
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
      args:
        MODULE_PATH: user-service
    ports:
      - "8082:8082"
    environment:
      - USER_SERVICE_DB_URL=${USER_SERVICE_DB_URL}
      - USER_SERVICE_DB_USER=${USER_SERVICE_DB_USER}
      - USER_SERVICE_DB_PASS=${USER_SERVICE_DB_PASS}
      - USER_SERVICE_DB_NAME=${USER_SERVICE_DB_NAME}
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_SERVER_URL=http://service-discovery:8761/eureka/
      - PORT=8082
    depends_on:
      db:
        condition: service_healthy
      service-discovery:
        condition: service_started
  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
      args:
        MODULE_PATH: notification-service
    ports:
      - "8083:8083"
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_SERVER_URL=http://service-discovery:8761/eureka/
      - PORT=8083
      - KAFKA_SERVER=broker:29092
    depends_on:
      - service-discovery
  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
      args:
        MODULE_PATH: product-service
    ports:
      - "8084:8084"
    environment:
      - PRODUCT_SERVICE_DB_URL=${PRODUCT_SERVICE_DB_URL}
      - PRODUCT_SERVICE_DB_USER=${PRODUCT_SERVICE_DB_USER}
      - PRODUCT_SERVICE_DB_PASS=${PRODUCT_SERVICE_DB_PASS}
      - PRODUCT_SERVICE_DB_NAME=${PRODUCT_SERVICE_DB_NAME}
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_SERVER_URL=http://service-discovery:8761/eureka/
      - PORT=8084
      - KAFKA_SERVER=broker:29092
    depends_on:
      db:
        condition: service_healthy
      service-discovery:
        condition: service_started
  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
      args:
        MODULE_PATH: order-service
    ports:
      - "8085:8085"
    environment:
      - ORDER_SERVICE_DB_URL=${ORDER_SERVICE_DB_URL}
      - ORDER_SERVICE_DB_USER=${ORDER_SERVICE_DB_USER}
      - ORDER_SERVICE_DB_PASS=${ORDER_SERVICE_DB_PASS}
      - ORDER_SERVICE_DB_NAME=${ORDER_SERVICE_DB_NAME}
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_SERVER_URL=http://service-discovery:8761/eureka/
      - PORT=8085
      - KAFKA_SERVER=broker:29092
    depends_on:
      db:
        condition: service_healthy
      service-discovery:
        condition: service_started
  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
      args:
        MODULE_PATH: payment-service
    ports:
      - "8086:8086"
    environment:
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_URL=${VNPAY_URL}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
      - VNPAY_IPN_URL=${VNPAY_IPN_URL}
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - EUREKA_SERVER_URL=http://service-discovery:8761/eureka/
      - PORT=8086
      - KAFKA_SERVER=broker:29092
    depends_on:
      - service-discovery
  frontend:
    build:
      context: ./clothesWebsite
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

volumes:
  mysql_data: