apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
data:
  ORDER_SERVICE_DB_URL: "amRiYzpteXNxbDovL2RiOjMzMDYvb3JkZXItc2VydmljZQ=="
  ORDER_SERVICE_DB_USER: "cm9vdA=="
  ORDER_SERVICE_DB_PASS: "c2VjcmV0"
  ORDER_SERVICE_DB_NAME: "b3JkZXItc2VydmljZQ=="