apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      nodeSelector:
        agentpool: powerfulpool
      containers:
      - name: payment-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "800m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        image: quochuy1304acrregistry.azurecr.io/payment-service:latest
        ports:
        - containerPort: 8086
        env:
          - name: VNPAY_TMN_CODE
            valueFrom:
              secretKeyRef:
                name: payment-secret
                key: VNPAY_TMN_CODE
          - name: VNPAY_HASH_SECRET
            valueFrom:
              secretKeyRef:
                name: payment-secret
                key: VNPAY_HASH_SECRET
          - name: VNPAY_URL
            valueFrom:
              secretKeyRef:
                name: payment-secret
                key: VNPAY_URL
          - name: VNPAY_IPN_URL
            valueFrom:
              secretKeyRef:
                name: payment-secret
                key: VNPAY_IPN_URL
          - name: VNPAY_RETURN_URL
            valueFrom:
              secretKeyRef:
                name: payment-secret
                key: VNPAY_RETURN_URL
          - name: ZIPKIN_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: ZIPKIN_ENDPOINT
          - name: EUREKA_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: EUREKA_SERVER_URL
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: payment-config
                key: PORT
          - name: JAVA_OPTS
            value: "-XX:+UseG1GC"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: paymentservice
spec:
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: paymentservice
  type: ClusterIP