apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
data:
  PRODUCT_SERVICE_DB_URL: "amRiYzpteXNxbDovL215c3FsZGJxdW9jaHV5Lm15c3FsLmRhdGFiYXNlLmF6dXJlLmNvbTozMzA2L3Byb2R1Y3Qtc2VydmljZT91c2VTU0w9dHJ1ZQ=="
  PRODUCT_SERVICE_DB_USER: "aHV5YWRtaW4="
  PRODUCT_SERVICE_DB_PASS: "c2VjcmV0"
  PRODUCT_SERVICE_DB_NAME: "cHJvZHVjdC1zZXJ2aWNl"