apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
data:
  USER_SERVICE_DB_URL: "amRiYzpteXNxbDovL2RiOjMzMDYvcHJvZHVjdC1zZXJ2aWNl"
  USER_SERVICE_DB_USER: "cm9vdA=="
  USER_SERVICE_DB_PASS: "c2VjcmV0"
  USER_SERVICE_DB_NAME: "cHJvZHVjdC1zZXJ2aWNl"